<a href="https://colab.research.google.com/github/arundhathivnath/learn.py/blob/main/TASK%208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [2]:
#please provide your answer below this line.
import numpy as np
Y = np.random.rand(3,3)
print(Y)

[[0.65293409 0.50233227 0.42937969]
 [0.44212971 0.84031562 0.42713801]
 [0.95752386 0.53935412 0.01808734]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [3]:
#please provide your answer below this line.
import numpy as np
a = np.arange(3,19).reshape(4,4)
print(a)
b = np.arange(2,18).reshape(4,4)
print(b)
a = np.arange(3,19).reshape(2,8)
b = np.arange(2,18).reshape(2,8)
c = np.vstack((a,b))
print(c)
d = np.hstack((a,b))
print(d)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]]
[[ 3  4  5  6  7  8  9 10  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 10 11 12 13 14 15 16 17]]
